name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches: master

jobs:
  latest:
    runs-on: ubuntu-latest

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx 1
        uses: docker/setup-buildx-action@v1
        id: builder1
      -
        name: Set up Docker Buildx 2
        uses: docker/setup-buildx-action@v1
        id: builder2
      -
        name: Set up Docker Buildx 3
        uses: docker/setup-buildx-action@v1
        id: builder3
      -
        name: Build and push Latest
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder1.outputs.name }}
          target: mytarget1
          push: true
          build-args: |
            COMP_VER=latest
          tags: |
            bowens/docker-php-composer-builder:latest
      -
        name: Build and push 2.x
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder2.outputs.name }}
          target: mytarget2
          push: true
          build-args: |
            COMP_VER=2.0.7
          tags: |
            bowens/docker-php-composer-builder:2.0.7
      -
        name: Build and push 1.x
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder3.outputs.name }}
          target: mytarget3
          push: true
          build-args: |
            COMP_VER=1.10.17
          tags: |
            bowens/docker-php-composer-builder:1.10.17
      - 
        name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Integration Test # default: 8398a7@action-slack
          fields: repo,commit,message,author # default: repo,commit
          mention: here
          if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
